CREATE TABLE Students
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	NIM VARCHAR(20) NOT NULL,
	Nama VARCHAR(100) NOT NULL,
	Jurusan VARCHAR(100) NOT NULL,
	Gender VARCHAR(20) NOT NULL,
	Email VARCHAR(100)
);
